image: alpine/3.20
packages:
  - nodejs
  - npm
secrets:
  - e2e843cf-6f7e-4b74-989f-819a97ca70b8
  - 693e186a-109b-4e62-9d15-a123679909cc
sources:
  - git+ssh://git@git.sr.ht/~mattmundell/codemirror-lang-nasl
environment:
  PKG: codemirror-lang-nasl
tasks:
  - mirror: |
      cd $PKG && .bin/mirror
  - publish: |
      cd $PKG && .bin/publish
