image: alpine/3.20
packages:
  - nodejs
secrets:
  - e2e843cf-6f7e-4b74-989f-819a97ca70b8
sources:
  - git+ssh://git@git.sr.ht/~mattmundell/codemirror-lang-nasl
tasks:
  - check: |
      cd codemirror-lang-nasl
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      cd codemirror-lang-nasl
      git remote add github git@github.com:cookshack/codemirror-lang-nasl.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
  - publish: |
      cd codemirror-lang-nasl
      node --version
      export CURRENT=$(npm view @cookshack/codemirror-lang-nasl version)
      export VERSION=$(npm pkg get version)
      echo CURRENT: $CURRENT
      echo VERSION: $VERSION
      if [ "$CURRENT" != "$VERSION" ]; then \
        echo Publishing... \
      fi
