image: alpine/3.20
packages:
  - nodejs
  - npm
secrets:
  - e2e843cf-6f7e-4b74-989f-819a97ca70b8
  - 693e186a-109b-4e62-9d15-a123679909cc
sources:
  - git+ssh://git@git.sr.ht/~mattmundell/codemirror-lang-nasl
tasks:
  - check: |
      cd codemirror-lang-nasl
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      cd codemirror-lang-nasl
      git remote add github git@github.com:cookshack/codemirror-lang-nasl.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
  - publish: |
      cd codemirror-lang-nasl
      .bin/publish
