#!/usr/bin/env bash

# only mirror main
if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then
  echo Skipping mirror.
  exit
fi

export NAME=$(npm pkg get name | tr -d '"@')
echo NAME: $NAME
git remote add github git@github.com:$NAME.git
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
git push github main
